apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: susmitachart
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: oes
    chartVersion: 3.9.3

  #exclude: "repl{{ ConfigOptionEquals `include_chart` `include_chart_no`}}"

  # helmVersion identifies the Helm Version used to render the Chart. Default is v2.
  helmVersion: v3
  values:
    global:
      spinDeck:
        host: spinnaker.repl{{ ConfigOption `DN`}}
      spinGate:
        host: spinnaker-gate.repl{{ ConfigOption `DN`}}
      oesUI:
        host: oes.repl{{ ConfigOption `DN`}}
      oesGate:
        host: oes-gate.repl{{ ConfigOption `DN`}}


