apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-oes
spec:
  groups:
    - name: createIngress
      title: Expose OES/spin using an ingress 
      description: Expose OES/Spin using an ingress
      items:
        - name: createIngress
          title: Expose OES/spin using an ingress
          help_text: An example field to toggle inclusion of an Ingress Object
          type: bool
          default: "1"
    - name: spinDeck
      title: Enter Spin Deck URL
      description: "Spin Deck URL"
      items:
      - name: spindeck
        title: enter spin deck hostname
        help_text: An example field to toggle inclusion of an Ingress Object
        type: text
        default: "spin.example.ops.com"
        when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
      when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
    - name: spinGate
      title: Enter Spin Gate URL
      description: "Spin Gate URL"
      items:
      - name: spingate
        title: enter spin gate hostname
        help_text: An example field to toggle inclusion of an Ingress Object
        type: text
        default: "spin.example.ops.com"
        when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
      when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
    - name: oesUI
      title: Enter OES UI URL
      description: "OES UI URL"
      items:
      - name: oesui
        title: enter oes ui  hostname
        help_text: An example field to toggle inclusion of an Ingress Object
        type: text
        default: "oes.example.ops.com"
        when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
      when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
    - name: oesGate
      title: Enter OES Gate URL
      description: "OES Gate URL"
      items:
      - name: oesgate
        title: enter oes gate hostname
        help_text: An example field to toggle inclusion of an Ingress Object
        type: text
        default: "oes.example.ops.com"
        when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
    - name: genabled
      title: GitOps Style
      description: "Installs Spinnaker in GitOps Style"
      items:
        - name: genabled
          title: Install Spinnaker in GitOps Style
          help_text: Configures the Spinnaker using the files in Github
          type: bool
          default: "1"
    - name: repotype
      title: Repo Details
      description: "Enter repo Details as choosen"
      items:
      - name: repotype
        title: Repo Type
        type: select_one
        items:
        - name: git
          title: git
        - name: s3
          title: s3
        - name: stash
          title: stash
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: baseUrlHostName
      title: Base URL Hostname of the Repo 
      description: "Base URL Hostname of the Repo "
      items:
      - name: baseUrlHostName
        title: Enter BaseURL Hostname
        help_text: An example field to toggle inclusion of an Ingress Object
        type: text
        default: "github.com"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: organization
      title: Organization 
      description: Organization
      items: 
      - name: organization 
        title: Enter Organization Name
        type: text
        default: "OpsMx"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: projectName
      title: projectName
      description: projectName
      items:
      - name: projectName
        title: Enter ProjectName
        type: text
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: repository
      title: Name of Repository
      description: Name of Repository
      items:
      - name: repository
        title: Enter Repository Name
        type: text
        default: "standard-gitops-repo"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: dynamicAccRepository
      title: Name of Ext Acc Repository
      description: Name of Ext Acc Repository
      items:
      - name: dynamicAccRepository
        title: Name of External Accounts Repository
        type: text
        default: "standard-gitops-repo"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: halConfigPath
      title: Directory of Hal
      description: Directory of Hal
      items:
      - name: halConfigPath
        title: Directory of Hal
        type: text
        default: "/"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: dynAccntConfigPath
      title: Directory of Ext Accounts
      description: Directory of Ext Accounts
      items:
      - name: dynAccntConfigPath
        title: Directory of Ext Accounts
        type: text
        default: "dynaccount/"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: username
      title: UserName
      description: Git/Stash Username
      items:
      - name: username
        title: Git/Stash Username
        type: text
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: token
      title: Git/Stash Token
      description: Git/Stash Token
      items:
      - name: token
        title: Git/Stash Token
        type: password
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: s3accesskey
      title: AccessKey of User
      description: AccessKey of User
      items:
      - name: s3accesskey
        title: AccessKey of User
        type: text
        when: '{{repl (ConfigOptionEquals "repotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: s3secretkey
      title: secret Key of User
      description: Secret Key of User
      items:
      - name: s3secretkey
        title: Secret Key of User
        type: password
        when: '{{repl (ConfigOptionEquals "repotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: s3bucket
      title: s3 Bucket Name
      description: s3 Bucket Name
      items:
      - name: s3bucket
        title: s3 Bucket Name
        type: text
        when: '{{repl (ConfigOptionEquals "repotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: s3region
      title: s3 Region Name
      description: s3 Region Name
      items:
      - name: s3region
        title: s3 Region Name
        type: text
        when: '{{repl (ConfigOptionEquals "repotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: penabled
      title: pipelinePromotion for Spinnaker
      description: "Pipeline promotion to backup/syncup Pipelines from Repo"
      items:
        - name: penabled
          title: Pipeline Promotion for Spinnaker
          help_text: Backup/Syncup Pipelines in Spinnaker
          type: bool
          default: "1"
    - name: piperepotype
      title: Repo Details
      description: "Enter repo Details as choosen"
      items:
      - name: piperepotype
        title: Repo Type
        type: select_one
        items:
        - name: git
          title: git
        - name: s3
          title: s3
        - name: stash
          title: stash
        when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: porganization
      title: Organization 
      description: Organization
      items: 
      - name: porganization 
        title: Enter Organization Name for PipelinePromotion
        type: text
        default: "OpsMx"
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: prepository
      title: Repository
      description: Repository
      items: 
      - name: prepository
        title: Enter Repository Name
        type: text
        default: "standard-gitops-repo"
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: rootFolder
      title: root Folder Details
      description: rootFolder
      items: 
      - name: rootFolder
        title: Enter root Folder Details
        type: text
        default: "pipeline/"
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: baseUrl
      title: Base URL of the Repo 
      description: Base URL of the Repo
      items: 
      - name: baseUrl
        title: Enter URL of the Repo
        type: text
        default: "example.repo.com"
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: pusername
      title: UserName
      description: Git/Stash Username
      items:
      - name: pusername
        title: Git/Stash Username
        type: text
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: ptoken
      title: Git/Stash Token
      description: Git/Stash Token
      items:
      - name: ptoken
        title: Git/Stash Token
        type: password
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: branch
      title: BranchName
      description: BranchName
      items:
      - name: branch
        title: Branch
        type: text
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: usermail
      title: UserMail
      description: UserMail Details
      items:
      - name: usermail
        title: UserMail Details
        type: text
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: awsaccesskeyid
      title: AccessKey of User
      description: Access Key of User
      items:
      - name: awsaccesskeyid
        title: AccessKey of the User
        type: text
        when: '{{repl (ConfigOptionEquals "piperepotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: awssecretkeyid
      title: SecretKey of User
      description: Secret Key of User
      items:
      - name: awssecretkeyid
        title: Secret Key of the User
        type: password
        when: '{{repl (ConfigOptionEquals "piperepotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
