apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-oes
spec:
  groups:
    - name: createIngress
      title: Expose OES/spin using an ingress 
      description: Expose OES/Spin using an ingress
      items:
        - name: createIngress
          title: Expose OES/spin using an ingress
          help_text: Please make sure you create a DNS record before Installing
          type: bool
          default: "1"
    - name: DN
      title: Ingress Host details
      description: "Create a valid wildcard domain in DNS"
      items:
      - name: DN
        title: Enter valid Domain Name
        help_text: "Spinnaker is accessible on spinnaker.example.ops.com and oes on oes.example.ops.com and "
        type: text
        default: "example.ops.com"
        when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
      when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
    - name: frwderexternalName
      title: OES Agent 
      description: |
              "Use this if you want to configure an OES agent in the unaccessible remote cluster"
      items:
      - name: frwderexternalName
        title: Enter OES Agent server Hostname
        type: bool
        help_text: Agent will be accessible on the controller.example.ops.com
        default: "1"
        when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
      when: '{{repl (ConfigOptionEquals "createIngress" "1")}}'
    - name: installRedis
      title: Install Redis 
      description: Installs Bitnami Redis alongside OES
      items:
        - name: installRedis
          title: Install's Redis as a cache store for OES
          help_text: Please uncheck if you want to configure a Ext. Redis
          type: bool
          default: "1"
    - name: Enter Redis Details
      title: Enter Ext. Redis Details
      description: "Ext. Redis URL and Port are required"
      items:
      - name: externalhost
        title: Enter Redis URL
        type: text
        when: '{{repl (ConfigOptionEquals "installRedis" "0")}}'
      - name: externalport
        title: Enter NodePort for Spinnaker UI
        type: text
        default: "6379"
        when: '{{repl (ConfigOptionEquals "installRedis" "0")}}'
      when: '{{repl (ConfigOptionEquals "installRedis" "0")}}'
    - name: installOpenLdap
      title: Install OpenLdap for OES
      description: Installs OpenLdap as part of OES and configures authn and authz
      items:
        - name: installOpenLdap
          title: OpenLdap
          type: bool
          default: "1"
    - name: auth
      title: Authentication and Authorization Mechanism for OES
      description: "Autn and Autz Mechanisms to be used with OES"
      items:
      - name: auth
        type: select_one
        items:
        - name: ldap
          title: Ext. LDAP
        - name: saml
          title: SAML
        - name: oauth2
          title: OAUTH2
        when: '{{repl (ConfigOptionEquals "installOpenLdap" "0")}}'
      when: '{{repl (ConfigOptionEquals "installOpenLdap" "0")}}'
    - name: ldapdetails
      title: LDAP Details
      description: "Enter LDAP Details required to configure OES for authn and authz"
      items:
      - name: ldapurl
        title: Enter the external LDAP URL
        type: text
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "ldap")}}'
      - name: lmanagerdn
        title: Enter ManagerDN
        type: text
        default: "cn=admin,dc=example,dc=org"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "ldap")}}'
      - name: lmanagerpass
        title: Enter Manager Password
        type: password
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "ldap")}}'
      - name: groupsearchbase
        title: Enter Group Search Base
        type: text
        default: "ou=groups,dc=example,dc=org"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "ldap")}}'
      - name: groupsearchfilter
        title: Enter Group Search Filter
        type: text
        default: "member={0}"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "ldap")}}'
      - name: grouproleattr
        title: Enter Group Role Attributes
        type: text
        default: "cn"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "ldap")}}'
      - name: userdnpatt
        title: Enter User DN Pattern
        type: text
        default: "cn={0},dc=example,dc=org"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "ldap")}}'
      when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "ldap")}}'
    - name: samldetails
      title: SAML Details
      description: "Enter SAML Details required to configure OES for authn and authz. jksSecretName and metadataSecretName are to be preconfigured as the kubernetes secrets"
      items:
      - name: keyStorePassword
        title: Enter KeyStore Password
        type: password
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "saml")}}'
      - name: keyStoreAliasName
        title: Enter KeyStore Alias Name
        type: text
        default: "saml"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "saml")}}'
      - name: issuerId
        title: Enter Issuer ID of the SAML Application
        type: text
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "saml")}}'
      - name: userSource
        title: Enter UserSource for OES
        type: text
        default: "gate"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "saml")}}'
      - name: jksSecretName
        title: Enter JKS Secret Name
        type: text
        default: "oes-saml-jks"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "saml")}}'
      - name: metadataSecretName
        title: Enter the Metadata secret Name
        type: text
        default: "metadata-xml"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "saml")}}'
      when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "saml")}}'
    - name: oauth2details
      title: OAUTH2 Details
      description: "Enter OAUTH2 Details required to configure OES for authn and authz. jksSecretName and metadataSecretName are to be preconfigured as the kubernetes secrets"
      items:
      - name: clientId
        title: Enter Client ID
        type: text
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      - name: clientSecret
        title: Enter Client Secret
        type: text
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      - name: accessTokenUri
        title: Enter Access Token URL
        type: text
        default: "https://github.com/login/oauth/access_token"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      - name: userAuthorizationUri
        title: Enter User Authorization URI
        type: text
        default: "https://github.com/login/oauth/authorize"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      - name: scope
        title: Enter User Email
        type: text
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      - name: userInfoUri
        title: Enter User Info URI
        type: text
        default: "https://api.github.com/user"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      - name: useremail
        title: Enter User's EMAIL
        type: text
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      - name: userfname
        title: Enter User's FirstName
        type: text
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      - name: userlname
        title: Enter User's LastName
        type: text
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      - name: username
        title: Enter your Username
        type: text
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      - name: provider
        title: Enter name of your provider
        type: text
        default: "github"
        when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
      when: '{{repl and (ConfigOptionEquals "installOpenLdap" "0") (ConfigOptionEquals "auth" "oauth2")}}'
    - name: genabled
      title: GitOps Style
      description: "Installs Spinnaker in GitOps Style"
      items:
        - name: genabled
          title: Install Spinnaker in GitOps Style
          help_text: Configures the Spinnaker using the files in Github
          type: bool
          default: "1"
    - name: repotype
      title: Repo Details
      description: "Enter repo Details as choosen"
      items:
      - name: repotype
        title: Repo Type
        type: select_one
        items:
        - name: git
          title: git
        - name: s3
          title: s3
        - name: stash
          title: stash
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: baseUrlHostName
      title: Base URL Hostname of the Repo
      description: "Base URL Hostname of the Repo "
      items:
      - name: baseUrlHostName
        title: Enter BaseURL Hostname
        help_text: An example field to toggle inclusion of an Ingress Object
        type: text
        default: "github.com"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: organization
      title: Organization
      description: Organization
      items:
      - name: organization
        title: Enter Organization Name
        type: text
        default: "OpsMx"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: projectName
      title: projectName
      description: projectName
      items:
      - name: projectName
        title: Enter ProjectName
        type: text
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: repository
      title: Name of Repository
      description: Name of Repository
      items:
      - name: repository
        title: Enter Repository Name
        type: text
        default: "standard-gitops-repo"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: dynamicAccRepository
      title: Name of Ext Acc Repository
      description: Name of Ext Acc Repository
      items:
      - name: dynamicAccRepository
        title: Name of External Accounts Repository
        type: text
        default: "standard-gitops-repo"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: halConfigPath
      title: Directory of Hal
      description: Directory of Hal
      items:
      - name: halConfigPath
        title: Directory of Hal
        type: text
        default: "/"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: dynAccntConfigPath
      title: Directory of Ext Accounts
      description: Directory of Ext Accounts
      items:
      - name: dynAccntConfigPath
        title: Directory of Ext Accounts
        type: text
        default: "dynaccount/"
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: gusername
      title: UserName
      description: Git/Stash Username
      items:
      - name: gusername
        title: Git/Stash Username
        type: text
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: gtoken
      title: Git/Stash Token
      description: Git/Stash Token
      items:
      - name: gtoken
        title: Git/Stash Token
        type: password
        when: '{{repl or (ConfigOptionEquals "repotype" "git") (ConfigOptionEquals "repotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: s3accesskey
      title: AccessKey of User
      description: AccessKey of User
      items:
      - name: s3accesskey
        title: AccessKey of User
        type: text
        when: '{{repl (ConfigOptionEquals "repotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: s3secretkey
      title: secret Key of User
      description: Secret Key of User
      items:
      - name: s3secretkey
        title: Secret Key of User
        type: password
        when: '{{repl (ConfigOptionEquals "repotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: s3bucket
      title: s3 Bucket Name
      description: s3 Bucket Name
      items:
      - name: s3bucket
        title: s3 Bucket Name
        type: text
        when: '{{repl (ConfigOptionEquals "repotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: s3region
      title: s3 Region Name
      description: s3 Region Name
      items:
      - name: s3region
        title: s3 Region Name
        type: text
        when: '{{repl (ConfigOptionEquals "repotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "genabled" "1")}}'
    - name: penabled
      title: pipelinePromotion for Spinnaker
      description: "Pipeline promotion to backup/syncup Pipelines from Repo"
      items:
        - name: penabled
          title: Pipeline Promotion for Spinnaker
          help_text: Backup/Syncup Pipelines in Spinnaker
          type: bool
          default: "1"
    - name: piperepotype
      title: Repo Details
      description: "Enter repo Details as choosen"
      items:
      - name: piperepotype
        title: Repo Type
        type: select_one
        items:
        - name: git
          title: git
        - name: s3
          title: s3
        - name: stash
          title: stash
        when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: porganization
      title: Organization
      description: Organization
      items:
      - name: porganization
        title: Enter Organization Name for PipelinePromotion
        type: text
        default: "OpsMx"
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: prepository
      title: Repository
      description: Repository
      items:
      - name: prepository
        title: Enter Repository Name
        type: text
        default: "standard-gitops-repo"
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: rootFolder
      title: root Folder Details
      description: rootFolder
      items:
      - name: rootFolder
        title: Enter root Folder Details
        type: text
        default: "pipeline/"
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: baseUrl
      title: Base URL of the Repo
      description: Base URL of the Repo
      items:
      - name: baseUrl
        title: Enter URL of the Repo
        type: text
        default: "example.repo.com"
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: pusername
      title: UserName
      description: Git/Stash Username
      items:
      - name: pusername
        title: Git/Stash Username
        type: text
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: ptoken
      title: Git/Stash Token
      description: Git/Stash Token
      items:
      - name: ptoken
        title: Git/Stash Token
        type: password
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: pbranch
      title: BranchName
      description: BranchName
      items:
      - name: pbranch
        title: Branch
        type: text
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: pusermail
      title: UserMail
      description: UserMail Details
      items:
      - name: pusermail
        title: UserMail Details
        type: text
        when: '{{repl or (ConfigOptionEquals "piperepotype" "git") (ConfigOptionEquals "piperepotype" "stash")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: awsaccesskeyid
      title: AccessKey of User
      description: Access Key of User
      items:
      - name: awsaccesskeyid
        title: AccessKey of the User
        type: text
        when: '{{repl (ConfigOptionEquals "piperepotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'
    - name: awssecretkeyid
      title: SecretKey of User
      description: Secret Key of User
      items:
      - name: awssecretkeyid
        title: Secret Key of the User
        type: password
        when: '{{repl (ConfigOptionEquals "piperepotype" "s3")}}'
      when: '{{repl (ConfigOptionEquals "penabled" "1")}}'


